version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
    - ./app:/app  # maps the app directory in our project to the app directory in our docker image
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecret
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"  # this is needed to be able to connect via db GUI client
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data:
    driver: local
