version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: provision/docker/Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "cd backend &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/:delegated
    env_file:
      ./.env
    restart: on-failure:3
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"  # this is needed to be able to connect via db GUI client
    env_file:
      ./.env
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data:
    driver: local
