version: "3"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
    - ./app:/app  # maps the app directory in our project to the app directory in our docker image
    env_file:
      ./.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"  # this is needed to be able to connect via db GUI client
    env_file:
      ./.env
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data:
    driver: local
